# Generated by Django 6.0.1 on 2026-01-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
                ('active_from', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('active_to', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('sort', models.CharField(default='asc', max_length=255)),
                ('bitrix_elements_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
