# Generated by Django 6.0.1 on 2026-02-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['sort', 'id']},
        ),
        migrations.AlterField(
            model_name='collection',
            name='sort',
            field=models.CharField(default='500', max_length=255),
        ),
    ]
